### ISSUE TITLE
Serializing to h5ad times out

### ISSUE THREAD

**Issue by rroutsong** [the-ouyang-lab/ShinyCell2#7]
Continuing from #3 

Serializing v5 seurat objects to h5ad timesout.

**Comment by jfouyang** [comment]
Hi, it seems that issue #3 which involves assessing seurat5 Assay5 properly should be fixed with the pull request. Can you elaborate again what problems are you encountering in this issue?

Specifically, can you post the error message and type of data you are working on? (And do make sure you are using the latest version of shinycell2)

**Comment by rroutsong** [comment]
It fixed the labels but it never finishes saving the v5 object for me it will sit in the v5 saving portion of `makeH5fromSeurat.R` (up to 3 days as much as I have let it run)

My example data is CITEseq

> seu
An object of class Seurat
38753 features across 4169 samples within 3 assays
Active assay: RNA (38606 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 2 other assays present: ADT, HTO
 4 dimensional reductions calculated: pca, umap, apca, adt.umap


The root cause could be unsupported meta data, but removing them has not proven successful so far.

I will follow up with more details Monday.

**Comment by rroutsong** [comment]
# Expected Behavior
After running `makeShinyFiles` files are made to initialize ShinyCell2 service

# Current Behavior
makeShinyFiles starts to execute, and drastically slows down around lines 177-180, still not finishing in 3 to 5 days time, although memory is not full and notthing is writing to disk

# Possible Solution
1. Alternative object structure (this is ADT + HTO + RNA)
   - Although many attempts have been made to differentially remove meta.data that could be interfering see `Steps to reproduce`
2. I believe this is a problem related to the structure of my object, that was previously compounded by the label bug in #3 , just not sure what explicitly is causing the slow down

# Steps to Reproduce

```
library(Seurat)
library(ShinyCell2)
shiny_app_dir <- "shinyapp"
project_name <- "GRS-459"
seur <- readRDS('seur_cluster.rds')
shinycell_config <- createConfig(seur)
remove_metas <- c('HTO_secondID', 'HTO_margin', 'HTO_classification',
                  'HTO_classification.global', 'RNA_snn_res.0.1', 'RNA_snn_res.0.2',
                  'RNA_snn_res.0.4', 'RNA_snn_res.0.6', 'RNA_snn_res.1', 
                  'RNA_snn_res.1.5', 'RNA_snn_res.2', 'HTO_maxID', 'nCount_HTO',
                  'nFeature_HTO', 'orig.ident', 'Sample', 'RNA_snn_res.0.8', 'ADT_snn_res.0.8')
for (meta in remove_metas) {
    shinycell_config <- delMeta(shinycell_config, meta)
}
print(shinycell_config)
makeShinyFiles(
    seur, 
    shinycell_config, 
    shiny.dir = shiny_app_dir,
    shiny.prefix = 'sc1',
    chunkSize = 500000
)
```

# Context (Environment)
```
> sessionInfo()
R version 4.4.2 (2024-10-31)
Platform: aarch64-apple-darwin20
Running under: macOS Ventura 13.7.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] ShinyCell2_1.0.0   RColorBrewer_1.1-3 future_1.49.0      readr_2.1.5
 [5] glue_1.8.0         gridExtra_2.3      ggplot2_3.5.2      R.utils_2.13.0
 [9] R.oo_1.27.1        R.methodsS3_1.8.2  reticulate_1.42.0  hdf5r_1.3.12
[13] Matrix_1.7-1       data.table_1.17.4  Seurat_5.3.0       SeuratObject_5.1.0
[17] sp_2.2-0

loaded via a namespace (and not attached):
 [1] deldir_2.0-4           pbapply_1.7-2          rlang_1.1.6
 [4] magrittr_2.0.3         RcppAnnoy_0.0.22       matrixStats_1.5.0
 [7] ggridges_0.5.6         compiler_4.4.2         spatstat.geom_3.4-1
[10] png_0.1-8              vctrs_0.6.5            reshape2_1.4.4
[13] stringr_1.5.1          pkgconfig_2.0.3        fastmap_1.2.0
[16] promises_1.3.2         tzdb_0.5.0             bit_4.6.0
[19] purrr_1.0.4            jsonlite_2.0.0         goftest_1.2-3
[22] later_1.4.2            spatstat.utils_3.1-4   irlba_2.3.5.1
[25] parallel_4.4.2         cluster_2.1.6          R6_2.6.1
[28] ica_1.0-3              stringi_1.8.7          spatstat.data_3.1-6
[31] parallelly_1.44.0      spatstat.univar_3.1-3  lmtest_0.9-40
[34] scattermore_1.2        Rcpp_1.0.14            tensor_1.5
[37] future.apply_1.11.3    zoo_1.8-14             sctransform_0.4.2
[40] httpuv_1.6.16          splines_4.4.2          igraph_2.1.4
[43] tidyselect_1.2.1       abind_1.4-8            codetools_0.2-20
[46] spatstat.random_3.4-1  miniUI_0.1.2           spatstat.explore_3.4-2
[49] listenv_0.9.1          lattice_0.22-6         tibble_3.2.1
[52] plyr_1.8.9             withr_3.0.2            shiny_1.10.0
[55] ROCR_1.0-11            Rtsne_0.17             fastDummies_1.7.5
[58] survival_3.7-0         polyclip_1.10-7        fitdistrplus_1.2-2
[61] pillar_1.10.2          KernSmooth_2.23-24     plotly_4.10.4
[64] generics_0.1.4         RcppHNSW_0.6.0         hms_1.1.3
[67] scales_1.4.0           globals_0.18.0         xtable_1.8-4
[70] lazyeval_0.2.2         tools_4.4.2            RSpectra_0.16-2
[73] RANN_2.6.2             dotCall64_1.2          cowplot_1.1.3
[76] tidyr_1.3.1            colorspace_2.1-1       nlme_3.1-166
[79] patchwork_1.3.0        cli_3.6.5              spatstat.sparse_3.1-0
[82] spam_2.11-1            viridisLite_0.4.2      dplyr_1.1.4
[85] uwot_0.2.3             gtable_0.3.6           digest_0.6.37
[88] progressr_0.15.1       ggrepel_0.9.6          htmlwidgets_1.6.4
[91] farver_2.1.2           htmltools_0.5.8.1      lifecycle_1.0.4
[94] httr_1.4.7             mime_0.13              bit64_4.6.0-1
[97] MASS_7.3-61
```

**Comment by rroutsong** [comment]
After further experimenting it seems to ~resolve~ avoid this issue if you remove the `"HTO"` assay. So it seems ShinyCell2 has a bug related to unsupported assays, even if the metadata for those assays is removed from the Shiny meta config or if you specify the assays to use at the `makeShinyFiles` level.

**Comment by jfouyang** [comment]
Hi, thanks for the detailed reply. I am still investigating this and will get back to you.

**Comment by jfouyang** [comment]
Hi, thanks for the detailed reply! It has been a busy period lately hence the slow reply. I tried to access the RDS link today but to no avail. You mind sharing the object again so I can work out the errors?
